# =========================
# MONITORS
# =========================

# Monitor Externo (OMEN) - À Direita, mas será o Principal (0x0)
monitor=HDMI-A-1, 2560x1440@144, 0x0, 1

# Monitor do Portátil - À Esquerda (coordenada negativa para o rato bater certo)
# Se o portátil está à esquerda do OMEN, ele fica em -1920x0
monitor=eDP-2, 1920x1080@144, -1920x0, 1

# =========================
# WORKSPACES - FIXED
# =========================

# Laptop (Corrigido para eDP-2)
workspace=1,monitor:eDP-2
workspace=3,monitor:eDP-2
workspace=5,monitor:eDP-2
workspace=7,monitor:eDP-2
workspace=9,monitor:eDP-2

# External monitor
workspace=2,monitor:HDMI-A-1
workspace=4,monitor:HDMI-A-1
workspace=6,monitor:HDMI-A-1
workspace=8,monitor:HDMI-A-1
workspace=10,monitor:HDMI-A-1
